name: sample-app-nextjs
region: nyc
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: sample-dockerfile-nextjs
    match:
      path:
        prefix: /
jobs:
- github:
    branch: main
    deploy_on_push: true
    repo: bikram20/next-self-host
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  kind: POST_DEPLOY
  name: next-self-host-db-setup
  dockerfile_path: Dockerfile.migration
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: bikram20/next-self-host
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: sample-dockerfile-nextjs

